### ISSUE TITLE
CDV has an issue with connecting to the AAC over SSL with Lets Encrypt Certificate.

### ISSUE THREAD

**Issue by WebDevBren** [SIMPATICOProject/CDV#7]
as per our Email conversation.

An Issue with the CDV and Lets Encrypt SSL Certificates, when the AAC is hosted with it's own SSL Certificate provided by LetsEncrypt, it fails to connect, as it seems to grab the wrong SSL Certificate. 

Trace: 

`eu.trentorise.smartcampus.profileservice.ProfileServiceException: eu.trentorise.smartcampus.network.RemoteException: hostname i
n certificate didn't match: <auth.sparta.simpatico-project.eu> != <atlasfinancialsolutions.com> OR <atlasfinancialsolutions.com
> OR <www.atlasfinancialsolutions.com>                                                                                         
 at eu.trentorise.smartcampus.profileservice.BasicProfileService.getBasicProfile(BasicProfileService.java:73)                  
 at it.eng.opsi.cdv.pdatamanager.simpatico.security.config.JerseyFilter.filter(JerseyFilter.java:42)                           
 at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)                                
 at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)                                 
 at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)                                                      
 at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)                                                    
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)                                                               
 at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)                                                               
 at org.glassfish.jersey.internal.Errors.process(Errors.java:315)                                                              
 at org.glassfish.jersey.internal.Errors.process(Errors.java:297)                                                              
 at org.glassfish.jersey.internal.Errors.process(Errors.java:267)                                                              
 at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)                                       
 at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)                                                  
 at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)                                        
 at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)                                               
 at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)                                                   
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)                                           
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)                                           
 at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)                                           
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)                          
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)                                  
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)                                                     
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)                          
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)                                  
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)                                        
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) 
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)                                     
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)                                              
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)                                               
 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)                                  
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)                                           
 at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)                                                    
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)                                                
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)                                
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)                            
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)                                        
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)                        
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                          
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                  
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)               
 at java.lang.Thread.run(Thread.java:745)                                                            
Caused by: eu.trentorise.smartcampus.network.RemoteException: hostname in certificate didn't match: <auth.sparta.simpatico-proj
ect.eu> != <atlasfinancialsolutions.com> OR <atlasfinancialsolutions.com> OR <www.atlasfinancialsolutions.com>                 
 at eu.trentorise.smartcampus.network.RemoteConnector.getJSON(RemoteConnector.java:153)                                        
 at eu.trentorise.smartcampus.network.RemoteConnector.getJSON(RemoteConnector.java:124)                                        
 at eu.trentorise.smartcampus.profileservice.BasicProfileService.getBasicProfile(BasicProfileService.java:70)                  
 ... 40 more                                                                                                                   
Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <auth.sparta.simpatico-project.eu> != <atlasfinanc
ialsolutions.com> OR <atlasfinancialsolutions.com> OR <www.atlasfinancialsolutions.com>                                        
 at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:220)                                                
 at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)                       
 at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:149)                                                
 at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:130)                                                
 at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:339)                                         
 at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:123)         
 at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:147)                                               
 at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:101)                               
 at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:381)                                
 at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)                                        
 at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:576)                                        
 at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:554)                                        
 at eu.trentorise.smartcampus.network.RemoteConnector.getJSON(RemoteConnector.java:137)                                        
 ... 42 more `

**Comment by enzosav** [comment]
Updated in MASTER eu.trentorise.smartcampus.profileservice.BasicProfileService (v2.2) pom references

**Comment by WebDevBren** [comment]
This has been solved, We here at Sparta ended up deducting that the overall issue was caused by our nginx ssl config,
